### ISSUE TITLE
utils.py path error

### ISSUE THREAD

**Issue by joelsjlee** [wjbmattingly/bulk-image-clustering#3]
I'm trying to run the demo.ipynb code and get this error when running the process_images function: 

FileNotFoundError: [Errno 2] No such file or directory: '`./demo/static/images/demo_images/0071.jpg`'

This seems to be an error with how the "`filename`" variable is create in `src/utils.py` where it seems to appending demo_images to the new_directory in addition to each filename.

Replacing line 68 in `src/utils.py`: `filename = d.uri.split("\\")[-1]` with `filename = d.uri.split("/")[-1]` seems to fix this problem, but I may be misunderstanding this line of code or what its purpose is. Otherwise the demo runs smoothly and the server is running.

**Comment by wjbmattingly** [comment]
Thanks! Yes, that error is coming from me coding this on Windows. I will use a better approach that will be OS-agnostic. I believe you are on a Mac? Unix and Linux structure their paths differently than windows.

Thanks for identifying this!

**Comment by wjbmattingly** [comment]
I have fixed it. Running some tests on a Linux system now with a fresh env. Will update here when I push a fix.

**Comment by wjbmattingly** [comment]
Issue now fixed
